name: Hext.js Build
on: [push]

jobs:
  hext_emscripten:
    name: Hext.js Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run
      run: ./scripts/github-actions/build.sh
    - if: ${{ github.event_name == 'push' }}
      run: >
        mkdir hext.js-${{ github.sha }}
        && cp hext.js hext.mjs hext-without-eval.js hext.js-${{ github.sha }}/
    - if: ${{ github.event_name == 'push' }}
      uses: actions/upload-artifact@v4
      with:
        name: hext.js-${{ github.sha }}
        path: hext.js-${{ github.sha }}
    - if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      run: cp -f hext.js hext.mjs hext-without-eval.js dist/
    - if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "auto update dist/ [Github Actions]"
        file_pattern: dist/hext.js dist/hext.mjs dist/hext-without-eval.js
