name: Hext.js Release
on: 
  push:
    # creates a release for any tag conforming to a
    # semver version, e.g., v1.0.0
    tags:
      - v*.*.*

jobs:
  hext_emscripten:
    name: Hext.js Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/hext.js,dist/hext.mjs"
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: true
        draft: false
        allowUpdates: true
